# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
Task.create(:name => 'コーヒー飲む', :content => '熱々にする', :user_id => 23, :current_state => 1 )
Task.create(:name => 'お湯沸かす', :content => '熱湯にする', :user_id => 23, :current_state => 1 )
Task.create(:name => '水入れる', :content => '綺麗な水入れる', :user_id => 23, :current_state => 1 )
